// AUTO-GENERATED by scripts/build-playbooks.mjs from src/agent/playbooks/*.md.
// Do not edit by hand — edit the markdown, then run `npm run playbooks:build`.
// tests/playbooks-sync.test.ts fails `npm run check` if this drifts from the markdown.

export type PlaybookId = "weekly-plan" | "decompose-assignment" | "forum-brief";

export interface Playbook {
  id: PlaybookId;
  title: string;
  trigger: string;
  output: string;
  procedure: string;
}

export const PLAYBOOKS: Playbook[] = [
  {
    id: "weekly-plan",
    title: "Weekly plan",
    trigger: "on-demand, weekly",
    output: "brief",
    procedure: `Goal: a day-by-day checklist for the next 7 days across every enrolled unit.

1. Call list_courses to see every enrolled unit (unit codes look like FIT2004).
2. For each active unit, call get_course_overview(course) to pull assessments due
   within 14 days with submission status, staff posts from the last 7 days, and the
   \`sources\` flags (moodle, ed, ontrack, email). If \`sources.ontrack\` is false, an
   OnTrack-style task source is not connected for that unit — do not guess at task
   state for it. If \`sources.moodle\` or \`sources.ed\` is false, say the unit has no
   data from that source instead of treating silence as "nothing due".
3. Call search_items with kind "email" and terms such as "extension", "reschedule",
   "due", "exam", "quiz" for unit codes that showed nothing unusual in step 2 — a
   deadline change sometimes only arrives by email.
4. Rank items by due date, then by effort (a report or project outranks a 5-minute
   quiz due the same day).
5. Lay out a checklist for each of the next 7 days, dated explicitly. Put multi-day
   work on earlier days rather than the day before it is due.
6. If two deadlines collide on the same day, or an assessment's submission status is
   "unknown" and no spec is available for it, list it under "Needs your input" and
   ask at most one clarifying question about the single most important ambiguity.
7. Save the result with save_plan("weekly", "<ISO week, e.g. 2026-W38>", <the plan
   text you are about to output>).
8. If nothing is due in the next 7 days and there is nothing to ask about, output
   exactly the line NOTHING_TO_REPORT instead of inventing filler.

Output: a one-line title, the per-day checklist, then a "Needs your input" section
(omit it entirely when there is nothing to ask).`,
  },
  {
    id: "decompose-assignment",
    title: "Decompose assignment",
    trigger: "assessment-due-window, on-demand",
    output: "brief and plan",
    procedure: `Goal: turn one assessment into a concrete day-by-day task list before it is due.

1. Identify the assessment. If the caller gave a source and item id, call
   get_item(source, itemId) directly. Otherwise call search_items(query, kind:
   "assessment", course: "<unit code>") with the assessment name or keywords from
   the request.
2. Read the full assessment body from get_item — it returns the body uncapped;
   never plan from a clipped summary.
3. Call get_course_overview(course) for the assessment's unit code and read its
   staffPosts (last 14 days) and emailMentions for posts or emails that reference
   this assessment by name (extensions, clarified rubric, moved due date). If
   \`sources.ontrack\` is false for the unit, note that no OnTrack-style task tracker
   is connected instead of assuming the assessment has no linked tasks there.
4. If the assessment's submission facet already shows "submitted" (or an
   equivalent completed status), stop here and output exactly NOTHING_TO_REPORT —
   there is nothing left to decompose.
5. If the assessment body is missing, or no due date can be confirmed from any
   source, say so plainly and ask the one question that would unblock the plan.
6. Otherwise split the remaining work into 3-7 concrete tasks (for example: read
   spec and rubric, design test cases, implement core logic, write the report
   section, submit and confirm receipt). Give each task an estimated hour count
   that sums to a realistic total for the assessment's weight.
7. Spread the tasks across the days remaining until the due date. Keep weekends
   lighter unless list_memory records a preference for working weekends.
8. Save the result with save_plan("assignment", "<source item_id of the
   assessment, e.g. campus-moodle:assessment:123>", <the plan text>).

Output: the unit code and assessment title, then the day-by-day task list with
hour estimates per task.`,
  },
  {
    id: "forum-brief",
    title: "Forum brief",
    trigger: "daily, on-demand",
    output: "brief",
    procedure: `Goal: report what teaching staff said on Ed since the last forum brief.

1. Call list_courses to see every active unit.
2. For each unit whose \`sources.ed\` is true (skip units with no Ed data — say so
   only if the caller asked about that specific unit), call
   list_staff_posts(course, since) with \`since\` set to the last forum brief's
   timestamp from the caller's context, or 24 hours ago when none is given. A
   thread already counts as staff-authored when its author role is staff, tutor
   or admin, or the thread is an announcement, or the thread is pinned —
   list_staff_posts already applies this filter, so do not re-derive it.
3. Group the results by unit. For each thread, write one line: what changed for
   the student (a new announcement, a staff reply, a pinned clarification) and
   its URL.
4. Skip any unit with nothing new — do not print a unit heading with zero
   threads under it.
5. If every unit has nothing new, output exactly the line NOTHING_TO_REPORT and
   nothing else.

Output: one heading per unit with new staff activity, one line per thread
underneath it.`,
  },
];
