#!/usr/bin/env node
// Builds the six MCP Apps widgets (ADR-0037) from src/widgets/*.
//
// Why this exists: a ui:// resource is one self-contained text/html string —
// there is no server inside the sandboxed iframe to fetch a separate
// stylesheet or script from, so theme.css and the shared JS modules
// (bridge.js, markdown.js, checklist.js, format.js) have to be inlined into
// each widget's HTML at build time. The source files stay small and testable
// (markdown.js etc. are also plain ES modules tests import directly); this
// script produces the shippable artifact. tests/widgets-sync.test.ts
// re-inlines everything independently and fails `npm run check` if
// src/widgets.generated.ts has drifted — see tests/playbooks-sync.test.ts
// for the same pattern with playbooks.
//
// Also writes widgets-preview/*.html: the same inlined widgets fed the
// fixtures in tests/fixtures/widgets/*.json, for visual review in a browser.
//
// Run after editing anything in src/widgets/:
//   npm run widgets:build

import { readFileSync, writeFileSync, mkdirSync, readdirSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "..");
const widgetsDir = path.join(root, "src/widgets");
const fixturesDir = path.join(root, "tests/fixtures/widgets");
const outFile = path.join(root, "src/widgets.generated.ts");
const previewDir = path.join(root, "widgets-preview");

// name (matches WIDGET_URIS in src/mcp/door-contracts.ts) -> html file, title,
// and the fixture that stands in for that tool's structuredContent in preview.
export const WIDGET_DEFS = [
  { name: "briefCard", file: "brief-card.html", title: "Briefs", fixture: "brief-card.json" },
  { name: "courseView", file: "course-view.html", title: "Course", fixture: "course-view.json" },
  { name: "changesFeed", file: "changes-feed.html", title: "Changes", fixture: "changes-feed.json" },
  { name: "planChecklist", file: "plan-checklist.html", title: "Plan", fixture: "plan-checklist.json" },
  { name: "deadlineTimeline", file: "deadline-timeline.html", title: "Deadlines", fixture: "deadline-timeline.json" },
  { name: "connectionStatus", file: "connection-status.html", title: "Connections", fixture: "connection-status.json" },
];

// Shared modules are dual-mode (see markdown.js's header comment): plain ES
// exports for `import` in tests, and a `window.Unicorn.*` assignment for
// inlining as a classic (non-module) script. Stripping the `export` keyword
// here is what makes the second mode a plain script — the function/const
// declarations behind it are untouched.
const SHARED_JS_FILES = ["bridge.js", "markdown.js", "checklist.js", "format.js", "prompts.js"];

function stripExports(source) {
  return source.replace(/^export (function|const|class)\s/gm, "$1 ");
}

export function readSharedStyles() {
  return readFileSync(path.join(widgetsDir, "theme.css"), "utf8");
}

export function readSharedScript() {
  return SHARED_JS_FILES.map((file) => stripExports(readFileSync(path.join(widgetsDir, file), "utf8"))).join("\n");
}

// Inlines theme.css into the `/* UNICORN:THEME */` marker and the shared JS
// into `/* UNICORN:SHARED */`. Fails loudly if a widget template has drifted
// and lost a marker — a silently-un-inlined widget would ship broken.
export function inlineWidget(templateHtml, styles, script) {
  if (!templateHtml.includes("/* UNICORN:THEME */")) {
    throw new Error("widget template is missing the /* UNICORN:THEME */ marker");
  }
  if (!templateHtml.includes("/* UNICORN:SHARED */")) {
    throw new Error("widget template is missing the /* UNICORN:SHARED */ marker");
  }
  return templateHtml.replace("/* UNICORN:THEME */", styles).replace("/* UNICORN:SHARED */", script);
}

function escapeTemplate(text) {
  return text.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

export function buildGeneratedFile(widgets) {
  const entries = widgets
    .map((widget) => `  ${widget.name}: \`${escapeTemplate(widget.html)}\`,`)
    .join("\n");

  return `// AUTO-GENERATED by scripts/build-widgets.mjs from src/widgets/*.
// Do not edit by hand — edit the sources, then run \`npm run widgets:build\`.
// tests/widgets-sync.test.ts fails \`npm run check\` if this drifts.

export type WidgetName =
  | "briefCard"
  | "courseView"
  | "changesFeed"
  | "planChecklist"
  | "deadlineTimeline"
  | "connectionStatus";

export const WIDGET_HTML: Record<WidgetName, string> = {
${entries}
};
`;
}

// Injects the preview fixture as window.__UNICORN_PREVIEW__ right after
// <head>, before any other script runs — bridge.js's init() reads it
// synchronously in standalone mode (no parent host to postMessage to).
//
// hostCapabilities defaults to a host that supports both ui/message and
// ui/update-model-context, so the ask-actions are visible for design review;
// tests/widgets-prompts.test.ts exercises the "host lacks it" side directly
// against detectCapabilities() instead of another preview variant.
function buildPreviewHtml(inlinedHtml, structuredContent, theme) {
  const fixture = JSON.stringify({
    structuredContent,
    hostContext: { theme },
    hostCapabilities: { message: { text: {} }, updateModelContext: { text: {} } },
  });
  const script = `<script>window.__UNICORN_PREVIEW__ = ${fixture};</script>`;
  return inlinedHtml.replace("<head>", `<head>\n    ${script}`);
}

function buildPreviewIndex(widgets) {
  const rows = widgets
    .map(
      (widget) => `
      <section class="preview-row">
        <h2>${widget.title}</h2>
        <div class="preview-pair">
          <iframe title="${widget.title} (light)" src="${widget.name}-light.html"></iframe>
          <iframe title="${widget.title} (dark)" src="${widget.name}-dark.html"></iframe>
        </div>
      </section>`,
    )
    .join("\n");

  return `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>unicorn widgets preview</title>
    <style>
      body { font-family: -apple-system, sans-serif; background: #dedede; margin: 0; padding: 24px; }
      h2 { font-size: 14px; margin: 0 0 8px; }
      .preview-row { margin-bottom: 32px; }
      .preview-pair { display: flex; gap: 16px; flex-wrap: wrap; }
      iframe { width: 380px; height: 560px; border: 1px solid #999; background: white; }
    </style>
  </head>
  <body>
    <p>Generated by scripts/build-widgets.mjs — do not edit by hand. Each widget also opens standalone at
      &lt;name&gt;-light.html / &lt;name&gt;-dark.html for resizing to 360px / 720px widths.</p>
${rows}
  </body>
</html>
`;
}

// Pure: reads every source and inlines each widget, but writes nothing.
// tests/widgets-sync.test.ts calls this to re-derive src/widgets.generated.ts
// independently, the same way tests/playbooks-sync.test.ts re-parses markdown.
export function buildWidgets() {
  const styles = readSharedStyles();
  const script = readSharedScript();

  return WIDGET_DEFS.map((def) => {
    const template = readFileSync(path.join(widgetsDir, def.file), "utf8");
    const html = inlineWidget(template, `\n      ${styles}\n    `, `\n      ${script}\n    `);
    const structuredContent = JSON.parse(readFileSync(path.join(fixturesDir, def.fixture), "utf8"));
    return { ...def, html, structuredContent };
  });
}

// Design-review-only edge-case fixtures, kept separate from the WIDGET_DEFS
// fixture each widget ships with: tests/fixtures/widgets/edge/<file-prefix>.<
// suffix>.json (e.g. "brief-card.long-title.json") renders as an extra
// <name>-<suffix>-<theme>.html preview, for checking truncation, empty
// states, and error states that the normal fixture doesn't exercise. Never
// read by buildWidgets() / widgets.generated.ts — preview-only.
const edgeFixturesDir = path.join(fixturesDir, "edge");

function readEdgeFixtures(filePrefix) {
  if (!existsSync(edgeFixturesDir)) return [];
  return readdirSync(edgeFixturesDir)
    .filter((file) => file.startsWith(`${filePrefix}.`) && file.endsWith(".json"))
    .map((file) => ({ suffix: file.slice(filePrefix.length + 1, -".json".length), file }));
}

function main() {
  const widgets = buildWidgets();

  writeFileSync(outFile, buildGeneratedFile(widgets));

  mkdirSync(previewDir, { recursive: true });
  for (const widget of widgets) {
    for (const theme of ["light", "dark"]) {
      writeFileSync(
        path.join(previewDir, `${widget.name}-${theme}.html`),
        buildPreviewHtml(widget.html, widget.structuredContent, theme),
      );
    }

    const filePrefix = widget.file.replace(/\.html$/, "");
    for (const edge of readEdgeFixtures(filePrefix)) {
      const structuredContent = JSON.parse(readFileSync(path.join(edgeFixturesDir, edge.file), "utf8"));
      for (const theme of ["light", "dark"]) {
        writeFileSync(
          path.join(previewDir, `${widget.name}-${edge.suffix}-${theme}.html`),
          buildPreviewHtml(widget.html, structuredContent, theme),
        );
      }
    }
  }
  writeFileSync(path.join(previewDir, "index.html"), buildPreviewIndex(widgets));

  console.log(`Wrote ${path.relative(root, outFile)} and widgets-preview/ from ${widgets.length} widget(s).`);
}

// Only run when invoked directly (`node scripts/build-widgets.mjs`), not when
// tests/widgets-sync.test.ts imports this module for its pure helpers.
if (import.meta.url === new URL(process.argv[1], "file:").href) {
  main();
}
