// AUTO-GENERATED by scripts/build-playbooks.mjs from playbooks/*.md.
// Do not edit by hand — edit the markdown, then run `npm run playbooks:build`.
// tests/playbooks-sync.test.ts fails `npm run check` if this drifts from the markdown.

import type { PlaybookName } from "./mcp/door-contracts";

// Identical to PlaybookName; kept as its own alias so this module has no other
// dependency on the door contracts than the one type it must never drift from.
export type PlaybookId = PlaybookName;

export interface PlaybookArgument {
  name: string;
  description: string;
  required: boolean;
}

export interface Playbook {
  id: PlaybookId;
  title: string;
  description: string;
  trigger: string;
  output: string;
  arguments: PlaybookArgument[];
  procedure: string;
}

export const PLAYBOOKS: Playbook[] = [
  {
    id: "decompose-assignment",
    title: "Decompose assignment",
    description: "Use when the user wants an assignment broken into a day-by-day task list, or to run the unicorn decompose-assignment routine. Reads the assessment and its course bucket, splits the remaining work into dated tasks, and saves the plan.",
    trigger: "on-demand; routine daily 08:00 local time",
    output: "brief and plan",
    arguments: [{ name: "assignment", description: "Optional \"source:itemId\" of one assessment to decompose (as returned by upcoming or search_items). Omit to scan every assessment due within 21 days that has no plan yet.", required: false }],
    procedure: `Goal: turn each assessment due soon into a concrete day-by-day task list, saved as a plan.

Door tools required: \`upcoming\`, \`search_items\`, \`course\`, \`get_plan\`, \`save_plan\`, \`write_brief\`. Source
MCPs (Ed, Moodle, canvas-mcp), if mounted, are optional enrichment for reading a spec or staff answers in
more detail — use them if available, but this procedure must complete on door tools alone.

Respect every line \`run_playbook\` returned under \`corrections\` (verbatim \`remember\` notes) — for example a
stated weekend-work preference overrides the default in step 6.

1. Build the candidate list.
   - If the \`assignment\` argument was given, treat it as the one candidate. If it already looks like
     \`source:itemId\`, use it directly. Otherwise call \`search_items({ query: assignment, kind:
     "assessment" })\` and take the best match.
   - Otherwise call \`upcoming({ days: 21 })\` and keep every item with a \`dueAt\` whose \`state\` is not a
     submitted or completed state.
2. For each candidate, form its plan subject as exactly \`"<source>:<itemId>"\` (for example
   \`campus-moodle:assessment:123\`). This must match character-for-character what \`save_plan\` and
   \`get_plan\` use for the same item, or the plan will silently duplicate instead of updating.
3. Call \`get_plan({ kind: "assignment", subject })\`. If a plan already exists (\`plan\` is not null), skip
   this candidate — it already has a plan; never overwrite one a human or an earlier run wrote.
4. For each remaining candidate, call \`course({ code })\` for its course. Read the matching bucket
   (\`course/<CODE>/<assignment-slug>\`) for the assessment's own item (the spec or body) and every item
   alongside it (staff answers on its thread). If a source MCP for that course is mounted, you may read
   the live spec there for more detail — never required.
5. If the assessment's body is empty or missing, and nothing in the bucket describes it, and no source
   MCP filled the gap either, do not invent a plan for it: note in the brief that its spec could not be
   found, and move to the next candidate.
6. Otherwise split the remaining work into 3-7 concrete tasks (for example: read spec and rubric, design
   test cases, implement core logic, write the report section, submit and confirm receipt). Give each
   task an estimated hour count that sums to a realistic total for the assessment's weight. Spread the
   tasks across the days remaining until \`dueAt\`, lighter on weekends unless a correction says otherwise.
7. Save with \`save_plan({ kind: "assignment", subject, content: "<the day-by-day task list as markdown,
   GitHub task syntax for each task>" })\`.
8. Write \`write_brief({ kind: "assignment-plan", subject, title: "<course code> — <assessment title>",
   body: "<the same task list>", idempotencyKey: subject })\`.
9. If there are no candidates at all (nothing due within 21 days lacks a plan, or the named \`assignment\`
   was not found), do not call \`save_plan\` or \`write_brief\` for it — there is nothing to save. Say so
   plainly instead.

When run interactively: tell the user which assessment(s) got a new plan and read out the day-by-day list
for each. For a named \`assignment\` argument that already had a plan, say so and show the existing plan
(via \`get_plan\`) instead of silently doing nothing.`,
  },
  {
    id: "forum-brief",
    title: "Forum brief",
    description: "Use when the user wants a summary of staff forum activity since the last check, or to run the unicorn forum-brief routine. Reads changes since the last forum brief and reports staff notices per course.",
    trigger: "on-demand; routine daily 18:00 local time",
    output: "brief",
    arguments: [{ name: "course", description: "Optional unit code to scope the brief to one course. Omit to cover every course.", required: false }],
    procedure: `Goal: report what teaching staff posted, and what changed on forum threads, since the last forum brief.

Door tools required: \`get_briefs\`, \`changes_since\`, \`write_brief\`, and \`course\` when a specific course is
named. Source MCPs (Ed, canvas-mcp), if mounted, are optional enrichment for reading a thread in full —
use them if available, but this procedure must complete on door tools alone.

Finding the cursor:
1. Call \`get_briefs({ unreadOnly: false, limit: 20 })\` and find the most recent brief with \`kind:
   "forum-brief"\` whose \`subject\` matches the scope of this run — the \`course\` argument if one was given,
   or \`"all"\` if not. Its \`body\` ends with a machine-readable line \`cursor: <n>\`; parse \`<n>\` as the
   starting cursor.
2. If no matching previous forum-brief exists, use starting cursor \`"0"\` — this is the first run for that
   scope, so every event counts as new.

Gathering changes:
3. Call \`changes_since({ cursor, limit: 200 })\`. While \`hasMore\` is true, call it again with the returned
   \`nextCursor\` and merge the events, up to 5 calls total — cap the work rather than looping forever on a
   noisy history.
4. Keep only events of type \`notice.posted\` or \`content.changed\`, and, when a \`course\` argument was
   given, only events whose \`course\` matches it case-insensitively.
5. Group the kept events by \`course\`. Write one line per event: what changed for the student (a new
   staff notice, an edited thread) and its \`url\`. For \`content.changed\`, say what changed using \`before\`
   and \`after\`, not just that something did.
6. Skip any course with nothing kept — never print a course heading with zero lines under it.

Writing the brief:
7. If nothing was kept across every course, still write the brief so the cursor advances and the next run
   does not re-scan the same window: the body is "Nothing new on the forums." followed by the machine
   line from step 9.
8. Otherwise the body is one heading per course with new activity, one line per event underneath, newest
   first.
9. End the body with the machine line \`cursor: <n>\`, where \`<n>\` is the highest cursor value seen across
   steps 3-4 (or the starting cursor from step 1-2 if nothing was seen).
10. Call \`write_brief({ kind: "forum-brief", subject: course ?? "all", title: "Forum brief — <course, or
    "all courses">", body: "<the body from steps 7-9>", idempotencyKey: "<subject>:<the new cursor>" })\`.
    The cursor inside the idempotency key means a retried call over the same window is a no-op, while the
    next run's larger cursor still gets its own brief.

When run interactively: tell the user how many courses had new forum activity and read the lines for
each; if nothing was new, say so in one sentence.`,
  },
  {
    id: "triage",
    title: "Triage",
    description: "Use when the user wants unlabelled course or life items sorted into buckets, or to run the unicorn triage routine. Labels items via the door's label_items tool without guessing at ambiguous ones.",
    trigger: "on-demand; routine daily 07:15 local time",
    output: "brief, only when something needs attention",
    arguments: [],
    procedure: `Goal: give every unlabelled item a bucket, and a topic when it is obvious, without ever guessing at a
course.

Door tools required: \`life\`, \`course\`, \`label_items\`, \`write_brief\`. Source MCPs, if mounted, are
optional enrichment for reading a thread or email in full when the title alone does not say enough — use
them if available, but this procedure must complete on door tools alone.

The five buckets, exactly these: \`course/<CODE>/<assignment-slug>\`, \`course/<CODE>/general\`,
\`life/events\`, \`life/admin\`, \`life/other\`.

1. Call \`life()\`. Its \`unlabeled\` list is your first candidate pool — non-course items nobody has
   labelled yet.
2. For every course you know about (from a \`course({ code })\` call earlier this session, or from the
   \`course\` field on any candidate item), call \`course({ code })\` and take its \`unlabeled\` list too.
3. Never touch an item whose \`labeledBy\` is already \`"client"\` — that was a deliberate human or agent
   decision; leave it alone even if you would have chosen differently. Only items with \`unlabeled: true\`
   and \`bucket: null\` are candidates.
4. For each candidate, decide:
   - If its \`course\` field is set and the content is clearly about one assignment (the title or snippet
     names an assessment, or it is a thread whose category matches one), bucket it
     \`course/<CODE>/<assignment-slug>\` — reuse the exact slug an existing bucket for that course already
     uses; never invent a second slug for the same assignment.
   - If its \`course\` field is set but it is general course chatter (lectures, exam logistics, nothing
     assignment-specific), bucket it \`course/<CODE>/general\`.
   - If it has no course and reads as a club, seminar, or career-fair style item, bucket it
     \`life/events\`.
   - If it has no course and reads as enrolment, fees, timetable, or an official administrative notice,
     bucket it \`life/admin\`.
   - Otherwise \`life/other\`. When you are not sure whether an item belongs to a course at all, or which
     course, choose \`life/other\` over guessing a course bucket — a wrong course bucket is worse than an
     honest "other".
   - Add a \`topic\` only when it is unambiguous from the title or snippet alone (for example "exam",
     "extension", "club", "career"). Leave it out rather than force one.
5. Call \`label_items({ items: [{ source, itemId, bucket, topic? }, ...] })\` once, in a single batch, for
   everything you decided in step 4. Do not call it once per item.
6. If a candidate remains genuinely ambiguous even after reading its snippet (and, if a source MCP is
   mounted, the full item there), leave it unlabelled rather than force a guess — omit it from step 5's
   batch entirely.
7. Write a brief only if something needs the user's attention: an unrecognised course code appeared
   repeatedly, or several items landed in \`life/other\` that look like they should belong to a course you
   know but you could not confirm which. If everything labelled cleanly with nothing left over, do not
   call \`write_brief\` at all.
8. When you do write one: \`write_brief({ kind: "triage", subject: "<today's ISO date>", title: "Triage —
   items needing a look", body: "<what you were not sure about, and why>", idempotencyKey: "<today's ISO
   date>" })\`.

When run interactively: tell the user how many items got labelled and into which buckets, in one line;
mention anything you left unlabelled and why.`,
  },
  {
    id: "weekly-plan",
    title: "Weekly plan",
    description: "Use when the user wants their week planned across every course, or to run the unicorn weekly-plan routine. Builds a 7-day checklist from due dates and course buckets, saves it as a plan, and files it as a brief.",
    trigger: "on-demand; routine Monday 07:30 local time",
    output: "brief",
    arguments: [],
    procedure: `Goal: a day-by-day checklist for the next 7 days across every course, saved as a plan and a brief.

Door tools required: \`upcoming\`, \`course\`, \`life\`, \`save_plan\`, \`write_brief\`. Source MCPs (Ed, Moodle,
canvas-mcp, Gmail), if mounted in this session, are optional enrichment only — use them to double-check
a deadline or skim a spec, but this procedure must complete using door tools alone if none are mounted
or a call fails.

Respect every line \`run_playbook\` returned under \`corrections\` — they are the user's own verbatim
\`remember\` notes and override the defaults below (for example "no work on Sundays").

1. Call \`upcoming({ days: 7 })\` for everything with a deadline in the next 7 days across every course.
2. Call \`upcoming({ days: 14 })\` too — an assignment due 8-14 days out that needs several days of work
   should already appear on this week's calendar.
3. For each course code you see, call \`course({ code })\` for the full bucket view: submission state,
   the staff answers on that assignment's thread, and general-bucket notices. This catches anything
   \`upcoming\` did not carry, such as a spec change flagged in a thread.
4. Call \`life()\` once for non-course deadlines (club events, admin dates) that belong in the week.
5. If a source MCP for a course is mounted, you may cross-check its spec or latest staff post there —
   never required, never blocking.
6. Rank everything by due date, then by effort: a report or project outranks a five-minute quiz due the
   same day.
7. Lay out a checklist for each of the next 7 days, dated explicitly (for example "Mon 29 Sep"). Put
   multi-day work on the earlier days, not the day before it is due. Use GitHub task syntax for every
   actionable line, for example \`- [ ] FIT3175: draft intro (Assignment 2)\`.
8. If two deadlines collide on the same day, or an item's state is unknown and nothing you called
   explains it, add it under a "Needs your input" heading and ask at most one clarifying question about
   the single most important ambiguity. Do not let it block the rest of the plan.
9. Save the checklist with \`save_plan({ kind: "weekly", subject: "<ISO week, e.g. 2026-W39>", content:
   "<the full markdown checklist>" })\`. Compute the ISO week from the date the playbook runs.
10. Write \`write_brief({ kind: "weekly-plan", subject: "<same ISO week>", title: "Weekly plan — <ISO
    week>", body: "<the checklist markdown>", idempotencyKey: "<same ISO week>" })\`. The idempotency key
    is the ISO week, so running this playbook twice in the same week never creates a duplicate — a
    repeated key is a no-op on the server, so make the call regardless of whether you think it is a
    repeat.
11. If nothing is due in the next 14 days and there is nothing to ask about, still call \`save_plan\` and
    \`write_brief\` with a plan that plainly says "Nothing due this week." Do not invent filler, and do not
    skip either call just because the week is quiet — a client reading \`get_plan\` needs a real row, not
    silence.

When run interactively: tell the user the ISO week the plan covers, how many items are on it, and read
out the "Needs your input" section if one exists.`,
  },
];
